### ISSUE TITLE
CloudExplorer 6.0 beta

### ISSUE THREAD

**Issue by cloudnavigator** [rusher81572/cloudExplorer#27]
hi Phillip,
I'm interested in testing your new work on CloudExplorer 6.0 prior to its release in September.
Thanks.
tim

**Comment by rusher81572** [comment]
Hello, Tim.

Thank you very much! I appreciate it. Here is the link to download v6.0.

https://foobar81572.s3.amazonaws.com/cloudExplorer-6.0.zip

**Comment by rusher81572** [comment]
Updated above link with latest build. Contains many small fixes, updated icons, and alignment.

**Comment by rusher81572** [comment]
Closing issue. Latest RC's are now available by upgrading the app in the 5.x version. "Help -> Check for Updates"
