### ISSUE TITLE
Where is the jar?

### ISSUE THREAD

**Issue by insign** [rusher81572/cloudExplorer#41]
I could not found the CloudExplorer.jar in the repository...

**Comment by rusher81572** [comment]
Hello, I just seen this message and did not get a notification for some reason. I apologize. I think you are downloading the source code and not the actual package release located under releases: https://github.com/rusher81572/cloudExplorer/releases/tag/7.0 The compiled version is in the zip file there. Here is a direct link: https://github.com/rusher81572/cloudExplorer/releases/download/7.0/cloudExplorer-7.0.zip
