### ISSUE TITLE
Text not displayed in the input fields

### ISSUE THREAD

**Issue by texpert** [rusher81572/cloudExplorer#52]
Hello!

I am running the downloaded cloudExplorer 8.21 on Ubuntu 16.10 x64. Below is the link to the screenshot - something's wrong with the fonts, I think:

https://s.mail.ru/7KsU/JitEFiAjp

**Comment by rusher81572** [comment]
Oh my. Thanks for reporting this. I wish that I got a notification that this issue was created. I will install Ubuntu and give it a look.

**Comment by rusher81572** [comment]
I think I fixed it in this release: https://cloudexplorer.s3.amazonaws.com/cloudExplorer-dev.zip  Can you please verify?

**Comment by texpert** [comment]
@rusher81572 , now it is OK! Great work!!

**Comment by rusher81572** [comment]
Thanks, I will merge it and publish the new version.
