### ISSUE TITLE
v10.01 does not show bucket contents

### ISSUE THREAD

**Issue by mittag** [rusher81572/cloudExplorer#56]
After entering correct authentication information, the bucket list is displayed. However, no contents of any buckets are displayed. The error in the console is

The bucket is in this region: null. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 4437C6BBFAC99FFE)

In v10.01 there is no field to specify the region in the account setup screen, although this field appears on the tutorial videos for older versions.

**Comment by rusher81572** [comment]
Hello @mittag .

Yes, the region field has been removed in 10.x. What AWS endpoint are you connecting to? What region does the bucket exist in? Are objects displayed when you connect to the endpoint where the bucket is in?

**Comment by rusher81572** [comment]
Hello @mittag.

I reproduce the issue and added better region detection in the 10.02 dev build: https://cloudexplorer.s3.amazonaws.com/cloudExplorer-dev.zip 

May you please test it out? If it is good, I will publish it.

**Comment by rusher81572** [comment]
Thanks for creating this bug. You helped make cloud explorer better than ever.

Here are the changes:

Added the option to specify the region when creating a bucket.
Better logic to work with buckets in different regions.

Published the 10.02 release.

You can upgrade to the new release by going to Help -> Check for updates

**Comment by maozhiyong** [comment]
Hello, when  entering the correct authentication information and  the endpoint is https://s3.cn-north-1.amazonaws.com.cn, the software does not show anything,i guess it does not connect to s3 server.

**Comment by rusher81572** [comment]
Thanks for reporting this issue. I do not see that endpoint as a valid S3 endpoint: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
