### ISSUE TITLE
What Java version is everyone using now?

### ISSUE THREAD

**Issue by rusher81572** [rusher81572/cloudExplorer#59]
Hello, Cloud Explorer Users.

The current stable release works with Java 8. I just committed the changes to support Java 9 and 10. The dev link in the README is now built for Java 9.

My questions to the community are: 

What version of Java are you using for your day to day work/personal machine?
What version of Java are you using with Cloud Explorer?
What version of Java do you want to use Cloud Explorer with?
Do you think I should publish another release just to support Java 10 or wait until Java 11 this fall?

Please respond to this issue with your answers and thoughts.

Thank you.

**Comment by ajira86** [comment]
I'm working on GNU/Linux Debian testing (Buster at this time). The repository provide openjdk 9 to execute applications. So, I tried with java 9 but using any other version compatible with my system is ok for me. Is there any interest to use a more recent version of Java for you ?

**Comment by rusher81572** [comment]
Thanks for the feedback. Cloud Explorer was compiled with JDK 8. I just want to make sure that users can use Cloud Explorer with the new  JDK's. Nobody has provided feedback or issues but yourself, thank you =). So you are saying that it works fine using JDK 9? If so, great news!
