### ISSUE TITLE
Upload not working.....

### ISSUE THREAD

**Issue by Suleman-Elahi** [rusher81572/cloudExplorer#61]
![image](https://user-images.githubusercontent.com/24384996/43205853-2bc0bf2e-8fd9-11e8-8593-ba685f647514.png)

When I hit the _Upload_ button, after selecting files, nothing happens. 

I was using Cloud Explorer on Windows 10 and everything is working except file uploading.......maybe i am getting something wrong here but I tried a lot still can't help. So, can you please help ?

**Comment by rusher81572** [comment]
Hello, thanks for reporting this. It is working fine for me. Are you connecting to Amazon S3 or some other S3 compatible storage? Does the problem persist when restarting Cloud Explorer?

**Comment by rusher81572** [comment]
@Suleman-Elahi , any update?

**Comment by Suleman-Elahi** [comment]
I think I lost track of this thread...... Yeas the upload it still not working... I have tried it so many times..... But if is working for you then maybe I am doing something wrong. I have added the GIF below. Please see I am uploading the file in right way. 

![clod explorer](https://user-images.githubusercontent.com/24384996/43817306-5f05021e-9af6-11e8-9f99-dd9095d21a22.gif)

**Comment by rusher81572** [comment]
Thanks. Are you connecting to AWS S3 or an S3 compatible service? I will download Windows 10 and give it a go.

**Comment by rusher81572** [comment]
Reproduced the issue, thanks for reporting this. This is resolved in the dev version, which just contains later SDK's and support for Java 10: https://cloudexplorer.s3.amazonaws.com/cloudExplorer-dev.zip

Will release 11.1 soon.

**Comment by rusher81572** [comment]
Version 12 has been released, you should be able to upgrade from the old version. If this is resolved, please update the article =)

**Comment by Suleman-Elahi** [comment]
Hey  .. thanks for fixing this.... the article has updated too !!!!

**Comment by rusher81572** [comment]
Thank you!
