### ISSUE TITLE
Project Appears Dead

### ISSUE THREAD

**Issue by evermorian** [rusher81572/cloudExplorer#66]
Download links return an AllAccessDisabled error in XML format.

**Comment by rusher81572** [comment]
Hi, I am no longer hosting the compiled .zip on my AWS account. I can not host it on GitHub due to the large file size. Until I find a more permanent solution due to the large file size, CloudExplorer will need to be built from source.

**Comment by rusher81572** [comment]
Releasing v14 tonight with fixed upgrade system
